# This rule is not used by the project cilium-dhcp-wanip-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the network.serialx.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cilium-dhcp-wanip-operator
    app.kubernetes.io/managed-by: kustomize
  name: publicipclaim-editor-role
rules:
- apiGroups:
  - network.serialx.net
  resources:
  - publicipclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.serialx.net
  resources:
  - publicipclaims/status
  verbs:
  - get
