---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumloadbalancerippools
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.serialx.net
  resources:
  - publicipclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.serialx.net
  resources:
  - publicipclaims/finalizers
  verbs:
  - update
- apiGroups:
  - network.serialx.net
  resources:
  - publicipclaims/status
  verbs:
  - get
  - patch
  - update
